const houses = [
  {
    id: "rent-1",
    purpose: "rent",
    title: "Sunny 2BHK Apartment",
    city: "Delhi",
    location: "Lajpat Nagar, Delhi",
    price: 18000,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 920,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
    description: "A clean 2BHK rental home near market, metro, and daily essentials.",
  },
  {
    id: "rent-2",
    purpose: "rent",
    title: "Budget Family Floor",
    city: "Noida",
    location: "Sector 62, Noida",
    price: 14500,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 1,
    area: 800,
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80",
    description: "Reasonable rent home for students, small families, and working professionals.",
  },
  {
    id: "rent-3",
    purpose: "rent",
    title: "Compact Studio Home",
    city: "Gurugram",
    location: "DLF Phase 3, Gurugram",
    price: 12000,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80",
    description: "Compact and affordable studio with quick office connectivity.",
  },
  {
    id: "rent-4",
    purpose: "rent",
    title: "Peaceful 3BHK Rental",
    city: "Jaipur",
    location: "Vaishali Nagar, Jaipur",
    price: 22000,
    bookingAmount: 1499,
    bedrooms: 3,
    bathrooms: 2,
    area: 1350,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
    description: "Spacious rental home in a calm locality with parking and balcony.",
  },
  {
    id: "buy-1",
    purpose: "buy",
    title: "Modern Independent House",
    city: "Delhi",
    location: "Rohini, Delhi",
    price: 6800000,
    bookingAmount: 25000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1650,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=80",
    description: "Ready-to-move house with modern interiors and good road access.",
  },
  {
    id: "buy-2",
    purpose: "buy",
    title: "Premium City Apartment",
    city: "Noida",
    location: "Sector 137, Noida",
    price: 5200000,
    bookingAmount: 21000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1420,
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    description: "Well-planned apartment in a gated society with amenities.",
  },
  {
    id: "buy-3",
    purpose: "buy",
    title: "Luxury Villa",
    city: "Gurugram",
    location: "Golf Course Road, Gurugram",
    price: 18500000,
    bookingAmount: 51000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    description: "Large villa with premium interiors, lawn space, and covered parking.",
  },
  {
    id: "buy-4",
    purpose: "buy",
    title: "Affordable Starter Home",
    city: "Jaipur",
    location: "Mansarovar, Jaipur",
    price: 3600000,
    bookingAmount: 15000,
    bedrooms: 2,
    bathrooms: 2,
    area: 980,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=80",
    description: "Good first home option with practical layout and peaceful surroundings.",
  },
  {
    id: "rent-5",
    purpose: "rent",
    title: "Delhi Builder Floor",
    city: "Delhi",
    location: "Malviya Nagar, Delhi",
    price: 26000,
    bookingAmount: 1499,
    bedrooms: 3,
    bathrooms: 2,
    area: 1250,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    description: "Spacious builder floor near metro, schools, and daily needs.",
  },
  {
    id: "rent-6",
    purpose: "rent",
    title: "Delhi Budget 1BHK",
    city: "Delhi",
    location: "Dwarka, Delhi",
    price: 13500,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 560,
    image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?auto=format&fit=crop&w=1000&q=80",
    description: "Affordable 1BHK for students and working professionals.",
  },
  {
    id: "rent-7",
    purpose: "rent",
    title: "Noida Gated Society Flat",
    city: "Noida",
    location: "Sector 76, Noida",
    price: 21000,
    bookingAmount: 1299,
    bedrooms: 3,
    bathrooms: 2,
    area: 1320,
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=1000&q=80",
    description: "Comfortable flat in a gated society with security and parking.",
  },
  {
    id: "rent-8",
    purpose: "rent",
    title: "Noida Studio Rental",
    city: "Noida",
    location: "Sector 18, Noida",
    price: 11000,
    bookingAmount: 699,
    bedrooms: 1,
    bathrooms: 1,
    area: 480,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1000&q=80",
    description: "Compact studio near offices, metro, malls, and restaurants.",
  },
  {
    id: "rent-9",
    purpose: "rent",
    title: "Gurugram Service Flat",
    city: "Gurugram",
    location: "Sector 56, Gurugram",
    price: 24500,
    bookingAmount: 1499,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80",
    description: "Well-maintained flat with balcony and office connectivity.",
  },
  {
    id: "rent-10",
    purpose: "rent",
    title: "Gurugram Family Apartment",
    city: "Gurugram",
    location: "Sushant Lok, Gurugram",
    price: 32000,
    bookingAmount: 1999,
    bedrooms: 3,
    bathrooms: 3,
    area: 1500,
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=80",
    description: "Family apartment with lift, parking, and a peaceful residential location.",
  },
  {
    id: "rent-11",
    purpose: "rent",
    title: "Jaipur Independent Floor",
    city: "Jaipur",
    location: "Malviya Nagar, Jaipur",
    price: 16500,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80",
    description: "Independent floor with easy access to markets and transport.",
  },
  {
    id: "rent-12",
    purpose: "rent",
    title: "Jaipur Compact Home",
    city: "Jaipur",
    location: "Jagatpura, Jaipur",
    price: 12000,
    bookingAmount: 699,
    bedrooms: 1,
    bathrooms: 1,
    area: 620,
    image: "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1000&q=80",
    description: "Reasonable rental home for students, couples, and small families.",
  },
  {
    id: "buy-5",
    purpose: "buy",
    title: "Delhi Premium 3BHK",
    city: "Delhi",
    location: "Pitampura, Delhi",
    price: 8200000,
    bookingAmount: 31000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1500,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80",
    description: "Premium apartment for families with modern layout and strong connectivity.",
  },
  {
    id: "buy-6",
    purpose: "buy",
    title: "Delhi Starter Apartment",
    city: "Delhi",
    location: "Uttam Nagar, Delhi",
    price: 4200000,
    bookingAmount: 18000,
    bedrooms: 2,
    bathrooms: 2,
    area: 850,
    image: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1000&q=80",
    description: "Affordable apartment for first-time buyers with practical space.",
  },
  {
    id: "buy-7",
    purpose: "buy",
    title: "Noida Ready Flat",
    city: "Noida",
    location: "Sector 78, Noida",
    price: 6100000,
    bookingAmount: 24000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1380,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=80",
    description: "Ready-to-move apartment in a society with lift, security, and parking.",
  },
  {
    id: "buy-8",
    purpose: "buy",
    title: "Noida Affordable 2BHK",
    city: "Noida",
    location: "Sector 121, Noida",
    price: 3900000,
    bookingAmount: 16000,
    bedrooms: 2,
    bathrooms: 2,
    area: 920,
    image: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1000&q=80",
    description: "Affordable 2BHK option for small families and first-home buyers.",
  },
  {
    id: "buy-9",
    purpose: "buy",
    title: "Gurugram Luxury Apartment",
    city: "Gurugram",
    location: "Sector 65, Gurugram",
    price: 12500000,
    bookingAmount: 45000,
    bedrooms: 4,
    bathrooms: 4,
    area: 2450,
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=80",
    description: "Luxury high-rise apartment with premium interiors and amenities.",
  },
  {
    id: "buy-10",
    purpose: "buy",
    title: "Gurugram Smart 2BHK",
    city: "Gurugram",
    location: "Sector 92, Gurugram",
    price: 5800000,
    bookingAmount: 22000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1000&q=80",
    description: "Smart 2BHK with modern fittings, society security, and parking.",
  },
  {
    id: "buy-11",
    purpose: "buy",
    title: "Jaipur Duplex Home",
    city: "Jaipur",
    location: "Vaishali Nagar, Jaipur",
    price: 7200000,
    bookingAmount: 28000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1750,
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1000&q=80",
    description: "Duplex home with spacious rooms, parking, and a peaceful neighbourhood.",
  },
  {
    id: "buy-12",
    purpose: "buy",
    title: "Jaipur Budget Apartment",
    city: "Jaipur",
    location: "Tonk Road, Jaipur",
    price: 3100000,
    bookingAmount: 14000,
    bedrooms: 2,
    bathrooms: 2,
    area: 880,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1000&q=80",
    description: "Budget apartment with simple layout and good city connectivity.",
  },
  {
    id: "rent-13",
    purpose: "rent",
    title: "Rishikesh River View Flat",
    city: "Rishikesh",
    location: "Tapovan, Rishikesh",
    price: 15500,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 860,
    image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1000&q=80",
    description: "Peaceful rental flat near cafes, yoga centers, and river walk areas.",
  },
  {
    id: "rent-14",
    purpose: "rent",
    title: "Rishikesh Studio Rental",
    city: "Rishikesh",
    location: "Laxman Jhula, Rishikesh",
    price: 9500,
    bookingAmount: 699,
    bedrooms: 1,
    bathrooms: 1,
    area: 430,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1000&q=80",
    description: "Affordable studio rental for students, solo workers, and long stays.",
  },
  {
    id: "rent-15",
    purpose: "rent",
    title: "Rishikesh Family Cottage",
    city: "Rishikesh",
    location: "Neelkanth Road, Rishikesh",
    price: 22000,
    bookingAmount: 1499,
    bedrooms: 3,
    bathrooms: 2,
    area: 1300,
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1000&q=80",
    description: "Family cottage rental surrounded by greenery and quiet local roads.",
  },
  {
    id: "rent-16",
    purpose: "rent",
    title: "Goa Furnished Apartment",
    city: "Goa",
    location: "Calangute, Goa",
    price: 28000,
    bookingAmount: 1499,
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=80",
    description: "Furnished apartment for monthly rent with kitchen, parking, and balcony.",
  },
  {
    id: "rent-17",
    purpose: "rent",
    title: "Goa Villa Portion",
    city: "Goa",
    location: "Candolim, Goa",
    price: 35000,
    bookingAmount: 1999,
    bedrooms: 3,
    bathrooms: 3,
    area: 1500,
    image: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1000&q=80",
    description: "Spacious villa portion for family rental with open sitting space.",
  },
  {
    id: "rent-18",
    purpose: "rent",
    title: "Goa Budget Studio",
    city: "Goa",
    location: "Anjuna, Goa",
    price: 16000,
    bookingAmount: 999,
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?auto=format&fit=crop&w=1000&q=80",
    description: "Budget studio rental for working professionals and small stays.",
  },
  {
    id: "buy-13",
    purpose: "buy",
    title: "Rishikesh Hill Cottage",
    city: "Rishikesh",
    location: "Tapovan, Rishikesh",
    price: 4800000,
    bookingAmount: 18000,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1000&q=80",
    description: "Compact cottage near hills, good for vacation home buyers.",
  },
  {
    id: "buy-14",
    purpose: "buy",
    title: "Rishikesh 2BHK Apartment",
    city: "Rishikesh",
    location: "Avas Vikas, Rishikesh",
    price: 3900000,
    bookingAmount: 15000,
    bedrooms: 2,
    bathrooms: 2,
    area: 880,
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80",
    description: "Practical 2BHK apartment for families and second-home buyers.",
  },
  {
    id: "buy-15",
    purpose: "buy",
    title: "Rishikesh Independent Home",
    city: "Rishikesh",
    location: "Shyampur, Rishikesh",
    price: 6200000,
    bookingAmount: 24000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1450,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    description: "Independent family home with parking and calm residential surroundings.",
  },
  {
    id: "buy-16",
    purpose: "buy",
    title: "Goa Holiday Apartment",
    city: "Goa",
    location: "Calangute, Goa",
    price: 5900000,
    bookingAmount: 22000,
    bedrooms: 2,
    bathrooms: 2,
    area: 920,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80",
    description: "Holiday apartment with rental income potential and good location.",
  },
  {
    id: "buy-17",
    purpose: "buy",
    title: "Goa Portuguese Villa",
    city: "Goa",
    location: "Anjuna, Goa",
    price: 9800000,
    bookingAmount: 38000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1000&q=80",
    description: "Portuguese-style villa with private rooms, kitchen, and open sit-out area.",
  },
  {
    id: "buy-18",
    purpose: "buy",
    title: "Goa Budget Home",
    city: "Goa",
    location: "Mapusa, Goa",
    price: 4300000,
    bookingAmount: 17000,
    bedrooms: 2,
    bathrooms: 2,
    area: 850,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=80",
    description: "Budget home option in Goa for small families and first-time buyers.",
  },
  {
    id: "stay-1",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Cozy Studio Stay",
    city: "Delhi",
    location: "Hauz Khas, Delhi",
    price: 1899,
    bookingAmount: 999,
    bedrooms: 1,
    bathrooms: 1,
    area: 430,
    image: "https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1000&q=80",
    description: "A neat studio for 1 or 2 night stays near cafes, metro, and markets.",
  },
  {
    id: "stay-2",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Day Use Apartment",
    city: "Noida",
    location: "Sector 18, Noida",
    price: 1499,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80",
    description: "Budget-friendly day stay apartment for rest, work, or short visits.",
  },
  {
    id: "stay-3",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Peaceful Farmhouse",
    city: "Gurugram",
    location: "Sohna Road, Gurugram",
    price: 4999,
    bookingAmount: 1499,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1000&q=80",
    description: "Private farmhouse for small family stays, birthdays, and weekend plans.",
  },
  {
    id: "stay-4",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Family Flat Stay",
    city: "Jaipur",
    location: "C-Scheme, Jaipur",
    price: 2599,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 980,
    image: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1000&q=80",
    description: "Comfortable 2BHK flat for tourists and families staying for 1-2 nights.",
  },
  {
    id: "stay-5",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Hill View Cottage",
    city: "Rishikesh",
    location: "Tapovan, Rishikesh",
    price: 3299,
    bookingAmount: 1299,
    bedrooms: 2,
    bathrooms: 2,
    area: 870,
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1000&q=80",
    description: "Relaxing cottage stay with hill views, balcony space, and calm surroundings.",
  },
  {
    id: "stay-6",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Goa Holiday Villa",
    city: "Goa",
    location: "Candolim, Goa",
    price: 3999,
    bookingAmount: 1499,
    bedrooms: 2,
    bathrooms: 2,
    area: 920,
    image: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1000&q=80",
    description: "A comfortable Goa villa near Candolim with bedrooms, kitchen, living space, and easy beach access.",
  },
  {
    id: "stay-7",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Delhi Work Stay Flat",
    city: "Delhi",
    location: "Saket, Delhi",
    price: 1599,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?auto=format&fit=crop&w=1000&q=80",
    description: "Simple day-use flat for work, rest, or short city visits in South Delhi.",
  },
  {
    id: "stay-8",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Delhi Family Guest House",
    city: "Delhi",
    location: "Karol Bagh, Delhi",
    price: 2399,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 820,
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=1000&q=80",
    description: "Family-friendly guest house with clean rooms, living area, and market access.",
  },
  {
    id: "stay-9",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Noida Couple Studio",
    city: "Noida",
    location: "Sector 75, Noida",
    price: 1799,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 480,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1000&q=80",
    description: "Compact studio stay in a gated society with basic kitchen and seating space.",
  },
  {
    id: "stay-10",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Noida Premium 2BHK",
    city: "Noida",
    location: "Sector 137, Noida",
    price: 2899,
    bookingAmount: 1199,
    bedrooms: 2,
    bathrooms: 2,
    area: 980,
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80",
    description: "Spacious 2BHK short stay for families and business travellers.",
  },
  {
    id: "stay-11",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Gurugram Office Stay",
    city: "Gurugram",
    location: "Cyber City, Gurugram",
    price: 1899,
    bookingAmount: 899,
    bedrooms: 1,
    bathrooms: 1,
    area: 560,
    image: "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1000&q=80",
    description: "Day stay near Cyber City for meetings, work breaks, and short rest.",
  },
  {
    id: "stay-12",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Gurugram Service Apartment",
    city: "Gurugram",
    location: "Sector 56, Gurugram",
    price: 2699,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80",
    description: "Clean service apartment with balcony, kitchen, and easy metro connectivity.",
  },
  {
    id: "stay-13",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Jaipur Heritage Room",
    city: "Jaipur",
    location: "Bani Park, Jaipur",
    price: 1299,
    bookingAmount: 699,
    bedrooms: 1,
    bathrooms: 1,
    area: 420,
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=80",
    description: "Budget heritage-style room for tourists needing a comfortable day stay.",
  },
  {
    id: "stay-14",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Jaipur Villa Stay",
    city: "Jaipur",
    location: "Malviya Nagar, Jaipur",
    price: 3499,
    bookingAmount: 1299,
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=80",
    description: "Private villa stay for families and groups with parking and open sitting area.",
  },
  {
    id: "stay-15",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Rishikesh Riverside Room",
    city: "Rishikesh",
    location: "Laxman Jhula, Rishikesh",
    price: 1599,
    bookingAmount: 799,
    bedrooms: 1,
    bathrooms: 1,
    area: 450,
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1000&q=80",
    description: "Peaceful room for day stays near cafes, yoga centers, and river walks.",
  },
  {
    id: "stay-16",
    purpose: "stay",
    stayType: "night",
    duration: "1 Night Stay",
    title: "Rishikesh Wooden Home",
    city: "Rishikesh",
    location: "Neelkanth Road, Rishikesh",
    price: 2899,
    bookingAmount: 999,
    bedrooms: 2,
    bathrooms: 2,
    area: 780,
    image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1000&q=80",
    description: "Wooden home stay surrounded by greenery, ideal for peaceful night stays.",
  },
  {
    id: "stay-17",
    purpose: "stay",
    stayType: "day",
    duration: "1 Day Stay",
    title: "Goa Studio Apartment",
    city: "Goa",
    location: "Calangute, Goa",
    price: 1999,
    bookingAmount: 899,
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=80",
    description: "A clean studio apartment for day use with AC, small kitchen, and parking.",
  },
  {
    id: "stay-18",
    purpose: "stay",
    stayType: "night",
    duration: "2 Night Stay",
    title: "Goa Portuguese House",
    city: "Goa",
    location: "Anjuna, Goa",
    price: 4599,
    bookingAmount: 1499,
    bedrooms: 3,
    bathrooms: 2,
    area: 1350,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1000&q=80",
    description: "Portuguese-style house with private rooms, kitchen, and quiet holiday vibe.",
  },
];

function wait(ms = 350) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function decodeGoogleCredential(credential) {
  const payload = credential.split(".")[1];
  const decodedPayload = atob(payload.replace(/-/g, "+").replace(/_/g, "/"));
  return JSON.parse(decodedPayload);
}

export async function signInWithGoogle(credential) {
  await wait();

  if (!credential) {
    throw new Error("Google sign-in failed.");
  }

  const profile = decodeGoogleCredential(credential);

  return {
    id: profile.sub,
    name: profile.name,
    email: profile.email,
    picture: profile.picture,
  };
}

export async function fetchHouses() {
  await wait();
  return houses;
}

export async function createPaymentOrder({ houseId, amount }) {
  if (!houseId || !amount) {
    throw new Error("Payment API error: house and amount are required.");
  }

  const response = await fetch("http://127.0.0.1:9000/payment/orders", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      amount: amount * 100,
      houseId,
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.message || "Payment order API failed.");
  }

  const order = await response.json();

  return {
    orderId: order.id,
    keyId: order.keyId,
    houseId,
    amount,
    currency: order.currency || "INR",
    status: order.status || "created",
  };
}

export async function verifyPaymentSuccess(paymentDetails) {
  const response = await fetch("http://127.0.0.1:9000/payment/success", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(paymentDetails),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.msg || error.message || "Payment verification failed.");
  }

  return response.json();
}
